# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: true
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Juan D. Collado Vasquez
org_slug: Juan D. Collado Vasquez
rebel_module_groups: []
repo_description: Compone varias extensiones para mejorar la experiencia del usuarion
    del elearning
repo_name: Extensiones para elearning de odoo
repo_slug: tgr-elearning
repo_website: https://github.com/cvjuan270/tgr-elearning
use_pyproject_toml: true
use_ruff: true

